server:
  port: 8761

spring:
  application:
    name: yvsjs-eureka-server

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
    fetch-registry: false
    register-with-eureka: false